import configparser
import logging

import discord
from discord.ext import commands

from datetime import datetime
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from models import Task

proxy_url = 'http://127.0.0.1:7890'
bot = commands.Bot(intents=discord.Intents.all(), proxy=proxy_url)
conf = configparser.ConfigParser()
conf.read('config.ini')

@bot.event
async def on_ready():
    logging.getLogger(__name__).debug(f"Logged in as mjwrap bot")

@bot.slash_command(description="Make DaVinci say something")
async def hello(ctx, sentence: discord.Option(str)):
    await ctx.respond(sentence)


@bot.slash_command(description="This command is a wrapper of MidJourneyAI")
async def mj_imagine(ctx, prompt: discord.Option(str)):
    logging.getLogger(__name__).debug(prompt)



@bot.slash_command(description="Upscale one of images generated by MidJourney")
async def mj_upscale(ctx, index: discord.Option(int), reset_target: discord.Option(bool) = True):
    logging.getLogger(__name__).debug('mj_upscale')

@bot.slash_command(description="Upscale to max targetted image (should be already upscaled using mj_upscale)")
async def mj_upscale_to_max(ctx):
    logging.getLogger(__name__).debug('mj_upscale_to_max')

@bot.slash_command(description="Make variation given index after target has been set")
async def mj_variation(ctx, index: discord.Option(int), reset_target: discord.Option(bool) = True):
    logging.getLogger(__name__).debug('mj_variation')


@bot.event
async def on_message(message):
    url=None
    for attachment in message.attachments:
        url=attachment.url
        break
    if url:
        engine = create_engine('sqlite:///./instance/test.db')
        Session = sessionmaker(bind=engine)
        session = Session()
        for t in session.query(Task).filter_by(prompt=message.content).all():
            if t.msgType==message.type.value and t.resultUrl is None:
                t.prompt = 'new prompt'
                t.updateTime = datetime.now()
                session.commit()
                session.close()
                break

bot.run(conf['discord']['token'])